spring:
  profiles:
    active: prod



logging:
  file:
    name: reactor-project-gateway.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 60

